#[cfg(feature = "cli")]
pub mod cli;
#[cfg(feature = "fmt")]
pub mod fmt;
#[cfg(feature = "in_memory")]
pub mod repository;
pub mod service;

mod error;
pub use error::*;

use crate::id::Id;
use crate::name::Name;
use crate::tag::Tags;

/// An Entity is anything which to interact with.
#[derive(Clone, Serialize, Deserialize)]
pub struct Entity {
    #[serde(flatten)]
    id: Id<Entity>,
    #[serde(flatten)]
    name: Name<Entity>,
    tags: Tags,
}

impl Eq for Entity {}
impl PartialEq for Entity {
    fn eq(&self, other: &Self) -> bool {
        self.id == other.id
    }
}

impl Entity {
    /// Creates a new entity with the given name and an autogenerated id.
    pub fn new(name: Name<Entity>) -> Self {
        Self {
            id: Id::new(),
            name,
            tags: Default::default(),
        }
    }

    /// Creates a new entity with the given id and name.
    pub fn with_id(id: Id<Entity>, name: Name<Entity>) -> Self {
        Self {
            id,
            name,
            tags: Default::default(),
        }
    }

    /// Returns a reference to the name of self.
    pub fn name(&self) -> &Name<Entity> {
        &self.name
    }
}
