#[cfg(feature = "cli")]
pub mod cli;
#[cfg(feature = "in_memory")]
pub mod repository;
pub mod service;

mod error;
pub use error::*;

use crate::{
    entity::Entity,
    id::{Id, Identifiable},
    interval::Interval,
    name::Name,
};
use serde::{Deserialize, Serialize};

/// An Event is a specific happening in which one or more entities are involved.
#[derive(Clone, Serialize, Deserialize)]
pub struct Event<Intv> {
    id: Id<Self>,
    name: Name<Self>,
    entities: Vec<Id<Entity>>,
    /// the interval is the time during which the event takes place.
    interval: Intv,
}

impl<Intv> Identifiable<Event<Intv>> for Event<Intv> {
    fn id(&self) -> Id<Self> {
        self.id
    }
}

impl<Intv> Interval for Event<Intv>
where
    Intv: Interval,
{
    type Bound = Intv::Bound;

    fn lo(&self) -> Self::Bound {
        self.interval.lo()
    }

    fn hi(&self) -> Self::Bound {
        self.interval.hi()
    }
}

impl<Intv> Event<Intv> {
    /// Creates an event with an autogenerated id.
    pub fn new(name: Name<Self>, interval: Intv) -> Self {
        Self {
            id: Id::new(),
            name,
            entities: Default::default(),
            interval,
        }
    }

    /// Creates a new event with the given id.
    pub fn with_id(id: Id<Self>, name: Name<Self>, interval: Intv) -> Self {
        Self {
            id,
            name,
            entities: Default::default(),
            interval,
        }
    }
}
